# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Basic formatting and checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Black code formatter
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: [--line-length=120]

  # Format docstrings using black
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies: ["black==24.2.0"]

  # Static code analysis
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--ignore=E712,E24,W504,W503,E203,E501']
        exclude: ^(tests/|scripts/|agrobusiness/migrations/)

  # Security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: [-lll, --recursive, .]

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=120]
        exclude: ^agrobusiness/migrations/

  # Docstring coverage
  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        args: [-vv, -i, --fail-under=60]
        exclude: ^(tests/|scripts/|agrobusiness/migrations/)

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args:
          - --disallow-any-generics
          - --disallow-untyped-calls
          - --disallow-untyped-defs
          - --disallow-incomplete-defs
          - --check-untyped-defs
          - --no-implicit-optional
          - --warn-redundant-casts
          - --warn-unused-ignores
          - --strict-equality
          - --ignore-missing-imports
        exclude: ^(tests/|scripts/|agrobusiness/migrations/)
